services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports: 
      - ${POSTGRES_PORT}:2701
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: ["/data/db"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080